nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/eslint-plugin@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/parser@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/typescript-estree@*":
    dependencies:
      typescript: "*"
  "@typescript-eslint/utils@*":
    dependencies:
      eslint: "*"
